// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

/**
 * @title EvidenceLocker
 * @dev Implements an immutable chain of custody for digital evidence using cryptographic hashes.
 */
contract EvidenceLocker {

    // --- Roles ---
    address public admin;
    mapping(address => bool) public investigators;
    mapping(address => bool) public custodians;
    mapping(address => bool) public auditors;

    // --- Structs ---
    struct Evidence {
        string evidenceId;      // e.g. "EV-0X889"
        string caseId;          // e.g. "CAS-2026-8921"
        string fileHash;        // SHA-256 fingerprint generated by the client
        uint256 timestamp;      // Block timestamp of registration
        address currentHolder;  // The user currently holding the physical/digital evidence
        string status;          // "Registered", "In Custody", "Under Analysis"
    }

    struct CustodyLog {
        address from;
        address to;
        uint256 timestamp;
        string action;          // e.g., "Transferred to Forensics"
    }

    // --- State Variables ---
    mapping(string => Evidence) public evidenceLedger;
    mapping(string => CustodyLog[]) public chainOfCustody;
    
    // Reverse mapping to see all evidence for a specific case
    mapping(string => string[]) public caseToEvidence;

    // --- Events ---
    event EvidenceRegistered(string indexed evidenceId, string indexed caseId, address indexed by);
    event CustodyTransferred(string indexed evidenceId, address indexed from, address indexed to, string action);

    // --- Modifiers ---
    modifier onlyAdmin() {
        require(msg.sender == admin, "Caller is not an Admin");
        _;
    }

    modifier onlyInvestigator() {
        require(investigators[msg.sender], "Caller is not an Investigator");
        _;
    }

    modifier onlyCustodian() {
        require(custodians[msg.sender], "Caller is not a Custodian");
        _;
    }

    modifier onlyAuditor() {
        require(auditors[msg.sender], "Caller is not an Auditor");
        _;
    }

    // --- Constructor ---
    constructor() {
        admin = msg.sender;
        investigators[msg.sender] = true;
        custodians[msg.sender] = true;
        auditors[msg.sender] = true;
    }

    // --- Admin Role Management ---
    function setInvestigator(address _user, bool _enabled) public onlyAdmin {
        investigators[_user] = _enabled;
    }

    function setCustodian(address _user, bool _enabled) public onlyAdmin {
        custodians[_user] = _enabled;
    }

    function setAuditor(address _user, bool _enabled) public onlyAdmin {
        auditors[_user] = _enabled;
    }

    // --- Core Functions ---

    /**
     * @dev Registers a new piece of evidence onto the blockchain.
     * @notice The actual file is NEVER stored here, only the SHA-256 hash.
     */
    function registerEvidence(
        string memory _evidenceId, 
        string memory _caseId, 
        string memory _fileHash
    ) public onlyInvestigator {
        // Ensure evidence doesn't already exist
        require(bytes(evidenceLedger[_evidenceId].evidenceId).length == 0, "Evidence ID already exists");

        // Create the record
        evidenceLedger[_evidenceId] = Evidence({
            evidenceId: _evidenceId,
            caseId: _caseId,
            fileHash: _fileHash,
            timestamp: block.timestamp,
            currentHolder: msg.sender,
            status: "Registered"
        });

        // Add to case mapping
        caseToEvidence[_caseId].push(_evidenceId);

        // Initial Custody Log
        chainOfCustody[_evidenceId].push(CustodyLog({
            from: address(0),
            to: msg.sender,
            timestamp: block.timestamp,
            action: "Initial Registration"
        }));

        emit EvidenceRegistered(_evidenceId, _caseId, msg.sender);
    }

    /**
     * @dev Transfers custody of evidence to a new authorized user.
     */
    function transferCustody(
        string memory _evidenceId, 
        address _newHolder, 
        string memory _actionDetails
    ) public {
        Evidence storage ev = evidenceLedger[_evidenceId];
        
        // Only the current holder can transfer it (unless admin override is needed in future)
        require(msg.sender == ev.currentHolder, "Only the current holder can transfer custody");

        // Execute Transfer
        ev.currentHolder = _newHolder;
        ev.status = "In Transfer";

        // Log the event immutably
        chainOfCustody[_evidenceId].push(CustodyLog({
            from: msg.sender,
            to: _newHolder,
            timestamp: block.timestamp,
            action: _actionDetails
        }));

        emit CustodyTransferred(_evidenceId, msg.sender, _newHolder, _actionDetails);
    }

    // --- View Functions (Useful for Auditors) ---
    
    function getEvidenceData(string memory _evidenceId) public view returns (Evidence memory) {
        return evidenceLedger[_evidenceId];
    }

    function getChainOfCustodyData(string memory _evidenceId) public view returns (CustodyLog[] memory) {
        return chainOfCustody[_evidenceId];
    }
}
