// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title EvidenceLocker
 * @dev Implements an immutable chain of custody for digital evidence using cryptographic hashes.
 *      Stores evidence metadata on-chain with IPFS CIDs for decentralized file storage.
 */
contract EvidenceLocker {

    // --- Roles ---
    address public admin;
    mapping(address => bool) public investigators;

    // --- Structs ---
    struct Evidence {
        string evidenceId;      // e.g. "EV-0X889"
        string caseId;          // e.g. "CAS-2026-8921"
        string fileHash;        // SHA-256 fingerprint generated by the client
        string ipfsCID;         // IPFS Content Identifier for the file
        uint256 timestamp;      // Block timestamp of registration
        address currentHolder;  // The user currently holding the physical/digital evidence
        string status;          // "Registered", "Modified", "In Custody"
        uint256 accessCount;    // Track total number of accesses
    }

    struct CustodyLog {
        address from;
        address to;
        uint256 timestamp;
        string action;          // e.g., "Modified", "Transferred"
        string note;
    }

    // --- State Variables ---
    mapping(string => Evidence) public evidenceLedger;
    mapping(string => CustodyLog[]) public chainOfCustody;
    mapping(string => string[]) public caseToEvidence;
    
    // Per-user access count for each evidence item
    mapping(string => mapping(address => uint256)) public userAccessCount;
    
    // Access permissions - which addresses are granted access to which evidence
    mapping(string => mapping(address => bool)) public accessPermissions;

    // --- Events ---
    event EvidenceUploaded(
        string indexed evidenceId, 
        string fileHash, 
        string ipfsCID, 
        address indexed uploaderAddress, 
        uint256 timestamp
    );
    
    event EvidenceModified(
        string indexed evidenceId, 
        string newHash, 
        string newIpfsCID, 
        address indexed modifierAddress, 
        uint256 timestamp, 
        string note
    );
    
    event AccessGranted(
        string indexed evidenceId, 
        address indexed grantedTo, 
        address indexed grantedBy, 
        uint256 timestamp
    );
    
    event EvidenceAccessed(
        string indexed evidenceId, 
        address indexed accessorAddress, 
        uint256 timestamp, 
        uint256 accessCountForUser
    );
    
    event CustodyTransferred(
        string indexed evidenceId, 
        address indexed from, 
        address indexed to, 
        string action
    );

    // --- Modifiers ---
    modifier onlyAdmin() {
        require(msg.sender == admin, "Caller is not an Admin");
        _;
    }

<<<<<<< Updated upstream
    modifier onlyInvestigator() {
        require(investigators[msg.sender], "Caller is not an Investigator");
        _;
    }

    modifier onlyCustodian() {
        require(custodians[msg.sender], "Caller is not a Custodian");
        _;
    }

    modifier onlyAuditor() {
        require(auditors[msg.sender], "Caller is not an Auditor");
        _;
    }

=======
>>>>>>> Stashed changes
    // --- Constructor ---
    constructor() {
        admin = msg.sender;
        investigators[msg.sender] = true;
<<<<<<< Updated upstream
        custodians[msg.sender] = true;
        auditors[msg.sender] = true;
    }

    // --- Admin Role Management ---
    function setInvestigator(address _user, bool _enabled) public onlyAdmin {
        investigators[_user] = _enabled;
    }

    function setCustodian(address _user, bool _enabled) public onlyAdmin {
        custodians[_user] = _enabled;
    }

    function setAuditor(address _user, bool _enabled) public onlyAdmin {
        auditors[_user] = _enabled;
=======
    }

    function addInvestigator(address _invest) public onlyAdmin {
        investigators[_invest] = true;
>>>>>>> Stashed changes
    }

    // --- Core Functions ---

    /**
     * @dev Registers a new piece of evidence onto the blockchain.
     */
    function registerEvidence(
        string memory _evidenceId, 
        string memory _caseId, 
        string memory _fileHash,
        string memory _ipfsCID
    ) public {
        require(bytes(evidenceLedger[_evidenceId].evidenceId).length == 0, "Evidence ID already exists");

        evidenceLedger[_evidenceId] = Evidence({
            evidenceId: _evidenceId,
            caseId: _caseId,
            fileHash: _fileHash,
            ipfsCID: _ipfsCID,
            timestamp: block.timestamp,
            currentHolder: msg.sender,
            status: "Registered",
            accessCount: 0
        });

        caseToEvidence[_caseId].push(_evidenceId);

        chainOfCustody[_evidenceId].push(CustodyLog({
            from: address(0),
            to: msg.sender,
            timestamp: block.timestamp,
            action: "Initial Registration",
            note: "Uploaded"
        }));

        emit EvidenceUploaded(_evidenceId, _fileHash, _ipfsCID, msg.sender, block.timestamp);
    }

    /**
     * @dev Modify an existing piece of evidence (e.g. replacing the file)
     */
    function modifyEvidence(
        string memory _evidenceId,
        string memory _newHash,
        string memory _newIpfsCID,
        string memory _note
    ) public {
        Evidence storage ev = evidenceLedger[_evidenceId];
        require(bytes(ev.evidenceId).length != 0, "Evidence does not exist");
        
        ev.fileHash = _newHash;
        ev.ipfsCID = _newIpfsCID;
        ev.timestamp = block.timestamp;
        ev.status = "Modified";

        chainOfCustody[_evidenceId].push(CustodyLog({
            from: ev.currentHolder,
            to: msg.sender,
            timestamp: block.timestamp,
            action: "Modified",
            note: _note
        }));

        emit EvidenceModified(_evidenceId, _newHash, _newIpfsCID, msg.sender, block.timestamp, _note);
    }

    /**
     * @dev Log an access event to the evidence
     */
    function accessEvidence(string memory _evidenceId) public {
        Evidence storage ev = evidenceLedger[_evidenceId];
        require(bytes(ev.evidenceId).length != 0, "Evidence does not exist");
        
        ev.accessCount += 1;
        userAccessCount[_evidenceId][msg.sender] += 1;
        
        emit EvidenceAccessed(_evidenceId, msg.sender, block.timestamp, userAccessCount[_evidenceId][msg.sender]);
    }

    /**
     * @dev Grant access to a specific address for an evidence item
     */
    function grantAccess(string memory _evidenceId, address _to) public {
        Evidence storage ev = evidenceLedger[_evidenceId];
        require(bytes(ev.evidenceId).length != 0, "Evidence does not exist");
        
        accessPermissions[_evidenceId][_to] = true;
        
        emit AccessGranted(_evidenceId, _to, msg.sender, block.timestamp);
    }

    /**
     * @dev Transfers custody of evidence
     */
    function transferCustody(
        string memory _evidenceId, 
        address _newHolder, 
        string memory _actionDetails
    ) public {
        Evidence storage ev = evidenceLedger[_evidenceId];
        require(bytes(ev.evidenceId).length != 0, "Evidence does not exist");
        require(msg.sender == ev.currentHolder, "Only holder can transfer");

        ev.currentHolder = _newHolder;
        ev.status = "In Transfer";

        chainOfCustody[_evidenceId].push(CustodyLog({
            from: msg.sender,
            to: _newHolder,
            timestamp: block.timestamp,
            action: _actionDetails,
            note: ""
        }));

        emit CustodyTransferred(_evidenceId, msg.sender, _newHolder, _actionDetails);
    }

    function getEvidenceData(string memory _evidenceId) public view returns (Evidence memory) {
        return evidenceLedger[_evidenceId];
    }

    function getChainOfCustodyData(string memory _evidenceId) public view returns (CustodyLog[] memory) {
        return chainOfCustody[_evidenceId];
    }
}
